services:
  node:
    build: .
    tty: true
    stdin_open: true
    entrypoint: ./docker-node.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
