services:
  node:
    build: .
    entrypoint: ./docker-node.sh
    ports:
      - "3000:3000"
      - "8443:8443"
      - "1935:1935"
    volumes:
      - .:/app:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
